
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: roboshop
  # these labels are replicaset labels
  labels:
    project: roboshop
    environment: dev
    tier: frontend
    component: frontend
spec:
  replicas: 1
  selector:
    # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      environment: dev
      tier: frontend
      component: frontend
  # This is pod definition, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tier: frontend
        component: frontend
    spec:
      containers:
      - name: frontend
        image: joindevops/frontend:1.4.0
        imagePullPolicy: Always # safe to pull everytime, there may be images with same version rebuilt and pushed
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          # httpGet:
          #   path: /health
          #   port: 8080
          tcpSocket:
            port: 80
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 15
        livenessProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 2
          periodSeconds: 10
        
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tier: frontend
    component: frontend
spec:
  type: LoadBalancer
  selector:
    # labels are used as selectors
    project: roboshop
    environment: dev
    tier: frontend
    component: frontend
  ports:
  - protocol: TCP
    port: 80 # servie port
    targetPort: 80 # container port