apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tier: backend
    component: cart
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
# labels are important

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tier: backend
    component: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      tier: backend
      component: cart
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tier: backend
        component: cart
    spec:
      containers:
      - name: cart
        image: vineethk08/cart:1.4.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 10
        livenessProbe: 
          httpGet: 
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: cart
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: cart
  labels:
    project: roboshop
    environment: dev
    tier: backend
    component: cart
spec: 
  selector:
      project: roboshop
      environment: dev
      tier: backend
      component: cart
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
      

      

