apiVersion: v1
kind: ConfigMap
metadata: 
  name: shipping
  namespace: roboshop
  labels: 
    project: roboshop
    environment: dev
    tier: backend
    component: shipping  
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tier: backend
    component: shipping  
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      tier: backend
      component: shipping  

  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tier: backend
        component: shipping 
    spec:
      containers:
      - name: shipping
        image: vineethk08/shipping:1.4.0
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "500"
            memory: "700Mi"
          limits:
            cpu: "200m"
            memory: "550Mi"
        readinessProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 15
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 10       
        envFrom:
        - configMapRef:
            name: shipping
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: shipping
  labels:
    project: roboshop
    environment: dev
    tier: backend
    component: shipping
spec:
  selector:
    project: roboshop
    environment: dev
    tier: backend
    component: shipping
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  











