apiVersion: v1
kind: ConfigMap
metadata: 
  namespace: roboshop
  name: rabbitmq
  labels:
    project: roboshop
    environment: dev
    tier: backend
    component: shipping  
data:
  RABBITMQ_DEFAULT_USER: roboshop
  RABBITMQ_DEFAULT_PASS: roboshop123

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq 
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tier: database
    component: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      tier: database
      component: rabbitmq
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tier: database
        component: rabbitmq
        env:
        - configMapRef:
          name: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: vineethk08/rabbitmq:3
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tier: database
    component: rabbitmq
spec:
  selector:
    project: roboshop
    environment: dev
    tier: database
    component: rabbitmq
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672

