apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: mongodb
  labels:
    project: roboshop
    environment: dev
    tier: database
    component: mongodb  
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      tier: database
      component: mongodb
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tier: database
        component: mongodb
    spec:
      containers:
      - name: mongodb
        image: vineethk08/mongodb:1.4.0
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: mongodb
  labels:
    project: roboshop
    environment: dev
    tier: database
    component: mongodb
spec:
  selector:
    project: roboshop
    environment: dev
    tier: database
    component: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017




