apiVersion: v1
kind: ConfigMap
metadata:
  namespace: roboshop
  name: catalogue
  labels:
    project: roboshop
    environment: dev
    tier: backend
    component: catalogue
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: catalogue
  labels:
    project: roboshop
    environment: dev
    tier: backend
    component: catalogue
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      tier: backend
      component: catalogue
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tier: backend
        component: catalogue
    spec:
      containers:
      - name: catalogue
        image: vineethk08/catalogue:1.4.0
        imagrPullPolicy: Always # safe to pull images everytime, there may be images with same versions rebuild and pushed
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        # Health check is mandatory 
        readinessProbe:
          # httpGet:
           # path: /health
           # port: 8080
          tcpSocket:
            port: 8080
          failureThreshold: 2
          periodSeconds: 10 
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 10       
        envFrom:
        - configMapRef:
            name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: catalogue
  labels:
    project: roboshop
    environment: dev
    tier: backend
    component: catalogue
spec:
  selector:
    project: roboshop
    environment: dev
    tier: backend
    component: catalogue
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  



