apiVersion: v1
kind: ConfigMap
metadata:
  namespace: roboshop
  name: catalogue
  labels:
    project: roboshop
    environment: dev
    tier: backend
    component: catalogue
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: catalogue
  labels:
    project: roboshop
    environment: dev
    tier: backend
    component: catalogue
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      tier: backend
      component: catalogue
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tier: backend
        component: catalogue
    spec:
      containers:
      - name: catalogue
        image: vineethk08/catalogue:1.0.0
        envFrom:
        - configMapRef:
            name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: catalogue
  labels:
    project: roboshop
    environment: dev
    tier: backend
    component: catalogue
spec:
  selector:
    project: roboshop
    environment: dev
    tier: backend
    component: catalogue
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  



