apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tier: backend
    component: user
data:
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"
  MONGO: "true"
# labels are important

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tier: backend
    component: user
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      tier: backend
      component: user
  template:
    metadata:
      labels:
        project: roboshop
        environment: dev
        tier: backend
        component: user
    spec:
      containers:
      - name: user
        image: vineethk08/user:1.4.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 10
        livenessProbe: 
          httpGet: 
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: user
---
apiVersion: v1
kind: Service
metadata:
  namespace: roboshop
  name: user
  labels:
    project: roboshop
    environment: dev
    tier: backend
    component: user
spec: 
  selector:
      project: roboshop
      environment: dev
      tier: backend
      component: user
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
      

      

